apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "syslog.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "syslog.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "syslog.fullname" . }}
    spec:
      containers:
      - name: syslog
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--no-caps"]
        volumeMounts:
        - mountPath: /etc/syslog-ng/syslog-ng.conf
          subPath: syslog-ng.conf
          name: config
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "syslog.fullname" . }}
