apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lcm.fullname" . }}-aws
data:
  aws.json: |
    {
      "application": "{{ .Values.spinnaker.application.name }}",
      "name": "Kubernetes AWS",
      "appConfig": {},
      "keepWaitingPipelines": false,
      "lastModifiedBy": "anonymous",
      "limitConcurrent": true,
      "parallel": true,
      "parameterConfig": [
        {
          "default": "3",
          "description": "Number of nodes",
          "name": "N"
        },
        {
          "name": "ENV_ID"
        },
        {
          "default": "false",
          "name": "DEBUG"
        },
        {
          "name": "AWS_ACCESS_KEY"
        },
        {
          "name": "AWS_SECRET_KEY"
        },
        {
          "name": "AWS_REGION"
        }
      ],
      "stages": [
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cxe",
              "ansible-playbook -e env_id=\"${ parameters.ENV_ID }\" /opt/playbooks/provision/playbook.yml"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "k8sprayorg",
              "registry": "index.docker.io",
              "repository": "k8sprayorg/ansible",
              "tag": "2.3.0.0"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Provision nodes",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "2",
          "requisiteStageRefIds": [
            "1"
          ],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "account": "local",
          "annotations": {},
          "application": "{{ .Values.spinnaker.application.name }}",
          "cloudProvider": "kubernetes",
          "cloudProviderType": "kubernetes",
          "container": {
            "args": [],
            "command": [
              "sh",
              "-cxe",
              "curl -d '{\"apocng_uuid\": \"${ parameters.ENV_ID }\", \"apocng_debug\": ${ parameters.DEBUG }, \"apocng_k8s_nodes\": ${ parameters.N }, \"apocng_aws\": {\"access_key\": \"${ parameters.AWS_ACCESS_KEY }\", \"secret_key\": \"${ parameters.AWS_SECRET_KEY }\", \"region\": \"${ parameters.AWS_REGION }\"}}' -k -f https://apocng-k8spray/api/store2/${ parameters.ENV_ID }/"
            ],
            "envVars": [],
            "imageDescription": {
              "account": "dockerhub",
              "fromTrigger": false,
              "organization": "appropriate",
              "registry": "index.docker.io",
              "repository": "appropriate/curl",
              "tag": "latest"
            },
            "name": "job",
            "volumeMounts": []
          },
          "labels": {},
          "name": "Prepare config",
          "namespace": "{{ .Release.Namespace }}",
          "refId": "1",
          "requisiteStageRefIds": [],
          "type": "runJob",
          "volumeSources": []
        },
        {
          "application": "{{ .Values.spinnaker.application.name }}",
          "failPipeline": true,
          "name": "Install Kubernetes",
          "pipeline": "${INSTALL_PIPELINE_ID}",
          "pipelineParameters": {
            "ENV_ID": "${ parameters.ENV_ID }"
          },
          "refId": "3",
          "requisiteStageRefIds": [
            "2"
          ],
          "type": "pipeline",
          "waitForCompletion": true
        }
      ],
      "triggers": []
    }