apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "lcm.fullname" . }}-install
  labels:
    app: {{ template "lcm.fullname" . }}-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      labels:
        app: {{ template "lcm.fullname" . }}-install
    spec:
      restartPolicy: OnFailure
      containers:
      - name: app
        image: "appropriate/curl"
        command:
        - curl
        - -f
        - -m
        - "10"
        - -d@/tmp/body/install.json
        - -X
        - POST
        - --header
        - "Content-Type: application/json"
        - --header
        - "Accept: application/json"
        - http://{{ template "lcm.gate-address" . }}/pipelines
        volumeMounts:
        - mountPath: /tmp/body
          name: pipeline
      volumes:
      - name: pipeline
        configMap:
          name: {{ template "lcm.fullname" . }}-install